name: ShellCheck CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.sh'
    types: [opened, synchronize, reopened]

jobs:
  shellcheck:
    if: github.head_ref == 'branch_of_huyle'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck on modified .sh files
        run: |
          # Lấy danh sách các file .sh đã thay đổi trong PR
          git diff --name-only origin/main...HEAD -- '*.sh' | xargs -r shellcheck
