name: ShellCheck CI

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.sh'
    types: [opened, synchronize, reopened]

jobs:
  shellcheck:
    if: github.head_ref == 'branch_of_huyle'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Paths Filter
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            shell_scripts:
              - '*.sh'

      - name: Install ShellCheck
        if: steps.filter.outputs.shell_scripts == 'true'
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck on modified .sh files
        if: steps.filter.outputs.shell_scripts == 'true'
        run: |
          for file in $(echo "${{ steps.filter.outputs.shell_scripts_files }}" | tr ',' '\n'); do
            shellcheck "$file"
          done
