name: Shell Script CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Kiểm tra mã nguồn của repo
      - name: Check out code
        uses: actions/checkout@v2
        
      # Cài đặt shellcheck để kiểm tra lỗi shell script
      - name: Set up shellcheck
        run: sudo apt-get install -y shellcheck
        
      # Tìm các tệp .sh đã thay đổi và kiểm tra lỗi cú pháp với shellcheck
      - name: Run ShellCheck on changed files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.sh$' || true)
          for FILE in $CHANGED_FILES; do
            echo "Running shellcheck on $FILE"
            shellcheck "$FILE"
          done

      # Kiểm tra lỗi runtime bằng cách thực thi script với Bash, dừng ngay nếu có lỗi
      - name: Execute changed scripts with Bash
        run: |
          set -e
          for FILE in $CHANGED_FILES; do
            if [[ -x "$FILE" ]]; then
              echo "Executing $FILE with Bash"
              bash "$FILE"
            else
              echo "Skipping $FILE (not executable)"
            fi
          done
