name: Shell Script CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      # Kiểm tra mã nguồn của repo
      - name: Check out code
        uses: actions/checkout@v2
        
      # Cài đặt shellcheck để kiểm tra lỗi shell script
      - name: Set up shellcheck
        run: sudo apt-get install -y shellcheck
        
      # Kiểm tra mã shell với shellcheck để phát hiện lỗi cú pháp
      - name: Run ShellCheck on changed files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '\.sh$' || true)
          for FILE in $CHANGED_FILES; do
            echo "Running shellcheck on $FILE"
            shellcheck "$FILE"
          done

      # Thực thi script với Bash, set -e sẽ dừng nếu gặp lỗi
      - name: Execute script with Bash
        run: |
          set -e
          chmod +x your_script.sh  # Đảm bảo script có quyền thực thi
          bash your_script.sh
