name: Shell Script CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Kiểm tra mã nguồn của repo
      - name: Check out code
        uses: actions/checkout@v2

      # Cài đặt shellcheck để kiểm tra lỗi shell script
      - name: Set up shellcheck
        run: sudo apt-get install -y shellcheck

      # Kiểm tra các file shell script thay đổi trong Pull Request hoặc Push
      - name: Run ShellCheck on changed files
        run: |
          set -e  # Dừng nếu có lỗi
          
          # Lấy danh sách các file thay đổi trong Pull Request (PR) hoặc Push lên main
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.before }} ${{ github.event.pull_request.after }} | grep '\.sh$' || true)
          
          # Nếu không có file .sh nào thay đổi, bỏ qua bước này
          if [ -z "$CHANGED_FILES" ]; then
            echo "No shell script files changed."
            exit 0
          fi
          
          # Chạy shellcheck cho mỗi file thay đổi
          for FILE in $CHANGED_FILES; do
            echo "Running shellcheck on $FILE"
            shellcheck "$FILE" || exit 1  # Nếu shellcheck phát hiện lỗi, dừng workflow và không cho phép merge
          done

      # Nếu có yêu cầu, có thể thêm bước để chạy script .sh sau khi kiểm tra
      - name: Execute changed shell scripts with Bash
        run: |
          set -e  # Dừng nếu có lỗi

          # Lấy danh sách các file thay đổi
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.before }} ${{ github.event.pull_request.after }} | grep '\.sh$' || true)

          # Nếu không có file .sh nào thay đổi, bỏ qua bước này
          if [ -z "$CHANGED_FILES" ]; then
            echo "No shell script files to execute."
            exit 0
          fi

          # Thực thi các file .sh thay đổi
          for FILE in $CHANGED_FILES; do
            echo "Executing $FILE with Bash"
            chmod +x "$FILE"   # Đảm bảo file có quyền thực thi
            bash "$FILE" || exit 1   # Dừng nếu script có lỗi, không cho phép merge
          done
